{% set version = "0.0.5" %}

package:
  name: plutosvg
  version: {{ version }}

source:
  url: https://github.com/sammycage/plutosvg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b82fa5e361d841a8c1c3471060d9b87148169d5401592c23be5084cfb3b825b5

build:
  number: 0
  run_exports:
    # 0-ver, so lets just pin to the patch version for now
    - {{ pin_subpackage('plutosvg', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    - plutovg
    - freetype
    - zlib

test:
  commands:
    - test -f ${PREFIX}/include/plutosvg/plutosvg.h                     # [unix]
    - test -f ${PREFIX}/lib/libplutosvg${SHLIB_EXT}                    # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/plutosvg.pc                      # [unix]
    - if not exist %PREFIX%\Library\include\plutosvg\plutosvg.h exit 1  # [win]
    - if not exist %PREFIX%\Library\lib\plutosvg.lib exit 1            # [win]
    - if not exist %PREFIX%\Library\lib\pkgconfig\plutosvg.pc exit 1   # [win]
    - if not exist %PREFIX%\Library\bin\plutosvg-0.dll exit 1          # [win]

about:
  home: https://github.com/sammycage/plutosvg
  summary: PlutoSVG is a compact and efficient SVG rendering library written in C.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
